// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Exiter is an autogenerated mock type for the Exiter type
type Exiter struct {
	mock.Mock
}

// Exit provides a mock function with given fields: code
func (_m *Exiter) Exit(code int) {
	_m.Called(code)
}
