// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Randomizer is an autogenerated mock type for the Randomizer type
type Randomizer struct {
	mock.Mock
}

// Randomize provides a mock function with given fields:
func (_m *Randomizer) Randomize() float64 {
	ret := _m.Called()

	var r0 float64
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}
