// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

import time "time"

// Sleeper is an autogenerated mock type for the Sleeper type
type Sleeper struct {
	mock.Mock
}

// Sleep provides a mock function with given fields: duration
func (_m *Sleeper) Sleep(duration time.Duration) {
	_m.Called(duration)
}
