required = [
  "github.com/alecthomas/gometalinter",
  "github.com/vektra/mockery/cmd/mockery",
  "github.com/cweill/gotests/gotests",
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/alecthomas/participle"
  version = "0.4.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.9.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.4.0"

[[constraint]]
  name = "github.com/spf13/afero"
  version = "1.2.2"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.2.6"

[[constraint]]
  name = "github.com/deckarep/golang-set"
  version = "1.7.1"

[[constraint]]
  name = "github.com/AlekSi/pointer"
  version = "1.1.0"
