[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/alecthomas/participle"
  version = "0.1.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"
