// Code generated by mockery v1.0.0. DO NOT EDIT.

package runtime

import mock "github.com/stretchr/testify/mock"

// MockCommand is an autogenerated mock type for the Command type
type MockCommand struct {
	mock.Mock
}

// Run provides a mock function with given fields: context
func (_m *MockCommand) Run(context Context) error {
	ret := _m.Called(context)

	var r0 error
	if rf, ok := ret.Get(0).(func(Context) error); ok {
		r0 = rf(context)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
