// Code generated by mockery v1.0.0. DO NOT EDIT.

package context

import mock "github.com/stretchr/testify/mock"

// MockMessageSender is an autogenerated mock type for the MessageSender type
type MockMessageSender struct {
	mock.Mock
}

// SendMessage provides a mock function with given fields: message
func (_m *MockMessageSender) SendMessage(message Message) {
	_m.Called(message)
}
