// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package context

import mock "github.com/stretchr/testify/mock"

// MockValueHolder is an autogenerated mock type for the ValueHolder type
type MockValueHolder struct {
	mock.Mock
}

// SetValue provides a mock function with given fields: name, value
func (_m *MockValueHolder) SetValue(name string, value interface{}) {
	_m.Called(name, value)
}
