// Code generated by mockery v1.0.0. DO NOT EDIT.

package context

import mock "github.com/stretchr/testify/mock"

// MockActorRegister is an autogenerated mock type for the ActorRegister type
type MockActorRegister struct {
	mock.Mock
}

// RegisterActor provides a mock function with given fields: actor, arguments
func (_m *MockActorRegister) RegisterActor(actor Actor, arguments []interface{}) {
	_m.Called(actor, arguments)
}
