// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package context

import mock "github.com/stretchr/testify/mock"

// MockStateHolder is an autogenerated mock type for the StateHolder type
type MockStateHolder struct {
	mock.Mock
}

// SetState provides a mock function with given fields: state
func (_m *MockStateHolder) SetState(state State) error {
	ret := _m.Called(state)

	var r0 error
	if rf, ok := ret.Get(0).(func(State) error); ok {
		r0 = rf(state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
