// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package interpreter

import mock "github.com/stretchr/testify/mock"

// MockWaitGroup is an autogenerated mock type for the WaitGroup type
type MockWaitGroup struct {
	mock.Mock
}

// Add provides a mock function with given fields: delta
func (_m *MockWaitGroup) Add(delta int) {
	_m.Called(delta)
}

// Done provides a mock function with given fields:
func (_m *MockWaitGroup) Done() {
	_m.Called()
}

// Wait provides a mock function with given fields:
func (_m *MockWaitGroup) Wait() {
	_m.Called()
}
