// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "github.com/thewizardplusplus/tick-tock/runtime/context"
import mapset "github.com/deckarep/golang-set"
import mock "github.com/stretchr/testify/mock"

// Context is an autogenerated mock type for the Context type
type Context struct {
	mock.Mock
}

// Copy provides a mock function with given fields:
func (_m *Context) Copy() context.Context {
	ret := _m.Called()

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// SendMessage provides a mock function with given fields: message
func (_m *Context) SendMessage(message context.Message) {
	_m.Called(message)
}

// SetMessageSender provides a mock function with given fields: sender
func (_m *Context) SetMessageSender(sender context.MessageSender) {
	_m.Called(sender)
}

// SetState provides a mock function with given fields: state
func (_m *Context) SetState(state context.State) error {
	ret := _m.Called(state)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.State) error); ok {
		r0 = rf(state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetStateHolder provides a mock function with given fields: holder
func (_m *Context) SetStateHolder(holder context.StateHolder) {
	_m.Called(holder)
}

// SetValue provides a mock function with given fields: name, value
func (_m *Context) SetValue(name string, value interface{}) {
	_m.Called(name, value)
}

// SetValueStore provides a mock function with given fields: store
func (_m *Context) SetValueStore(store context.CopyableValueStore) {
	_m.Called(store)
}

// Value provides a mock function with given fields: name
func (_m *Context) Value(name string) (interface{}, bool) {
	ret := _m.Called(name)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// ValuesNames provides a mock function with given fields:
func (_m *Context) ValuesNames() mapset.Set {
	ret := _m.Called()

	var r0 mapset.Set
	if rf, ok := ret.Get(0).(func() mapset.Set); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mapset.Set)
		}
	}

	return r0
}
