// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Waiter is an autogenerated mock type for the Waiter type
type Waiter struct {
	mock.Mock
}

// Add provides a mock function with given fields: delta
func (_m *Waiter) Add(delta int) {
	_m.Called(delta)
}

// Done provides a mock function with given fields:
func (_m *Waiter) Done() {
	_m.Called()
}

// Wait provides a mock function with given fields:
func (_m *Waiter) Wait() {
	_m.Called()
}
